workflows:
  android-workflow:
    name: Build Android APK
    instance_type: mac_mini_m2
    max_build_duration: 30
    scripts:
      - name: Generate Android project
        script: |
          flutter create . --project-name feel_issik --org tn.issik --platforms android
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
